site_name: Ultra-NX Wiki
copyright: Copyright &copy; 2024 Ultra-NX.
site_description: Ultra-NX CFW Guide.
site_author: Ultra-NX
site_url: https://ultra-nx.github.io/Wiki/
repo_url: https://github.com/Ultra-NX/Wiki
repo_name: Ultra-NX Wiki

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - toc.integrate
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tracking

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/wrench

nav:
    - Главная: index.md
    - Руководство пользователя:
        - 'Начало работы': 'user_guide/getting_started.md'
        - RCM:
          - 'Введение': 'user_guide/rcm/index.md'
          - 'Вход в RCM': 'user_guide/rcm/entering_rcm.md'
          - "Отправка payload'а": 'user_guide/rcm/sending_payload.md'
        - Модчип:
          - 'Введение': 'user_guide/modchip/index.md'
          - 'Подготовка Hekate': 'user_guide/modchip/preparing_hekate.md'
        - Завершение установки:
          - 'Выбор окружения': 'user_guide/all/cfw_environment.md'
          - 'Разметка microSD для emuMMC': 'user_guide/all/partitioning_sd.md'
          - 'Разметка microSD для sysCFW': 'user_guide/all/partitioning_sd_syscfw.md'
          - 'Подготовка microSD': 'user_guide/all/sd_preparation.md'
          - 'Создание необходимых резервных копий': 'user_guide/all/making_essential_backups.md'
          - 'Запуск CFW': 'user_guide/all/launching_cfw.md'
    - Homebrew:
      - 'Homebrew': 'homebrew/index.md'
      - 'JKSV': 'homebrew/jksv.md'
      - 'Goldleaf': 'homebrew/goldleaf.md'
      - 'FTPD': 'homebrew/ftpd.md'
      - 'NXTheme Installer': 'homebrew/nxtheme-installer.md'
      - 'NX-Shell': 'homebrew/nx-shell.md'
      - 'EdiZon': 'homebrew/edizon.md'
      - 'SimpleModManager': 'homebrew/simplemodmanager.md/'
      - 'Tesla-Menu': 'homebrew/tesla-menu.md'
      - 'MissionControl': 'homebrew/mission-control.md'
      - 'sys-con': 'homebrew/sys-con.md'
      - 'sys-botbase': 'homebrew/sys-botbase.md'
      - 'SysDVR': 'homebrew/sysdvr.md'
      - 'sys-clk': 'homebrew/sys-clk.md'
      - 'ldn_mitm': 'homebrew/ldn_mitm.md'
    - Инструкции:
        - 'Дополненительно': 'extras/index.md'
        - 'Блокировка серверов Nintendo': 'extras/blocking_nintendo.md'
        - 'Востановление бэкапа NAND': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - 'Модификация игр': 'extras/game_modding.md'
        - "Linux проброс payload'a без root прав": 'extras/adding_udev.md'
        - 'Показ расширений файлов (Windows)': 'extras/showing_file_extensions.md'
        - 'Альтернативные методы запуска': 'extras/alternate_bootsetups.md'
        - "Информация о донглах": 'extras/rcm_injectors.md'
        - 'Обновление CFW': 'extras/updating.md'
        - 'Смена SD карт': 'extras/transfer_sd.md'
        - 'Глоссарий': 'extras/glossary.md'
        - 'Установка Android': 'extras/installing_android.md'
        - 'Установка Linux': 'extras/installing_linux.md'
    - FAQ: faq.md
    - О нас: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
    - css/custom.css
